import type { Metadata } from "next";
import { Geist, Geist_Mono, Merriweather, Roboto } from "next/font/google";
import "./globals.css";
import "./base.css";
import "./new-font.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-merriweather",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} ${merriweather.variable} ${roboto.className} h-full antialiased`}
    >
      <body className={`${roboto.className} font-sans min-h-full flex flex-col`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
